Temp disable update unlisted job

diff --git a/.github/workflows/alert.yml b/.github/workflows/alert.yml
--- a/.github/workflows/alert.yml
+++ b/.github/workflows/alert.yml
@@ -9,10 +9,10 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
-    - name: Update unlisted
-      run: |
-        curl --fail https://born-to-llama.herokuapp.com/refresh
-        exit $?
+    # - name: Update unlisted
+    #   run: |
+    #     curl --fail https://born-to-llama.herokuapp.com/refresh
+    #     exit $?
     - name: Deploy to server
       run: |
         curl --fail https://born-to-llama.herokuapp.com/rebuild-server
